import "@/frontend/styles/globals.css";
import "@/frontend/styles/index.scss";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Juan Dahl Dev App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="h-screen w-full flex flex-col">{children}</div>
			</body>
		</html>
	);
}
